sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"  # points to 3.7 right now (2016-12-28)

matrix:
  fast_finish: true
  allow_failures:
    - python: "3.6"
    - python: "nightly"

install:
  - make travisci-install
script:
  - make travisci-test
after_success:
  - coveralls
